### ISSUE TITLE
Drag n drop doesn't work

### ISSUE THREAD

**Issue by PhoenixmitX** [elgatosf/streamdeck-pisamples#6]
https://user-images.githubusercontent.com/80752/153376059-8897cc53-67a5-4cd0-8e47-3f966c9d9c68.mp4

I am using Windows 10

**Comment by tiptronic** [comment]
?

**Comment by PhoenixmitX** [comment]
Edit:

It works, but under [releases](https://github.com/elgatosf/streamdeck-pisamples/releases) is not the newest version listed.

**Comment by tiptronic** [comment]
Hi @PhoenixmitX . Please do me a favour: if you comment something, please add your comment so I understand what you mean. The changes to the PISamples plugin sources just adds some changes to the Readme shown on GitHub and merges some css, both of which do not affect the 1.3's plugin-code at all. That's why there's no separate release.

**Comment by PhoenixmitX** [comment]
I used the 1.3 release and drag and drop didn't work.
After i upgraded to 1.4 from the [Release folder](https://github.com/elgatosf/streamdeck-pisamples/tree/master/Release) drag and drop worked for me.
